version: 2

jobs:
  test:
    docker:
      - image: web3f/node-dind:v3
      - image: parity/polkadot:latest
        name: polkadot
        command: --dev --rpc-port 11000 --rpc-external
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run tests
          command: |
            yarn test


  publishPackage:
    docker:
      - image: web3f/node-dind:v3
    steps:
      - checkout
      - run:
          name: Publish package
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            yarn
            yarn publish --access public

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publishPackage:
          context: npm-publisher
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
            branches:
              ignore: /.*/
          requires:
            - test
