version: 2

jobs:
  test:
    docker:
      - image: web3f/node:v0.1.0
      - image: parity/polkadot:v0.8.26 
        name: polkadot
        command: --chain=kusama-dev --ws-port 11000 --alice --ws-external --rpc-methods=Unsafe --rpc-cors=all
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run tests
          command: |
            yarn test


  publishPackage:
    docker:
      - image: web3f/node:v0.1.0
    steps:
      - checkout
      - run:
          name: Publish package
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            yarn
            yarn publish --access public

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publishPackage:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - test
